name: Build and Deploy to Docker Hub
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3
      # 2. Set up JDK for Gradle build
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
      # 3. Build the JAR file using Gradle
      - name: Build with Gradle
        run: ./gradlew build
      # 4. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # 5. Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/springboot-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/springboot-app:latest